In [1]:
import pandas as pd

In [29]:
df_2016 = pd.read_excel('2016_poblanos_state.xlsx')

In [30]:
df_2016 = df_2016.sort_values(by= 'state')

In [31]:
df_2015 = pd.read_excel('2015_poblanos_state.xlsx')
df_2015 = df_2015.sort_values(by= 'state')

In [32]:
df_2014 = pd.read_excel('2014_poblanos_state.xlsx')
df_2014 = df_2014.sort_values(by= 'state')

In [33]:
df_2013 = pd.read_excel('2013_poblanos_state.xlsx')
df_2013 = df_2013.sort_values(by= 'state')

In [34]:
df = pd.merge(df_2016, df_2015, on='state')
df

,state,amount_2016,percent_2016,amount_2015,percent_2015,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Alabama,199,0.003537,160,0.002087,NaN,NaN,NaN,NaN
1,Alaska,2,0.000036,8,0.000104,NaN,NaN,NaN,NaN
2,Arizona,273,0.004853,337,0.004397,NaN,NaN,NaN,NaN
3,Arkansas,193,0.003431,256,0.003340,NaN,NaN,NaN,NaN
4,California,15635,0.277911,22918,0.298995,NaN,NaN,NaN,NaN
5,Colorado,522,0.009279,575,0.007502,NaN,NaN,NaN,NaN
6,Connecticut,1295,0.023019,1969,0.025688,NaN,NaN,NaN,NaN
7,Delaware,284,0.005048,404,0.005271,NaN,NaN,NaN,NaN
8,District of Columbia,63,0.001120,103,0.001344,NaN,NaN,NaN,NaN
9,Florida,885,0.015731,1039,0.013555,NaN,NaN,NaN,NaN
10,Georgia,698,0.012407,991,0.012929,NaN,NaN,NaN,NaN
11,Hawaii,14,0.000249,16,0.000209,NaN,NaN,NaN,NaN
12,Idaho,79,0.001404,76,0.000992,NaN,NaN,NaN,NaN
13,Illinois,3286,0.058408,4063,0.053007,NaN,NaN,NaN,NaN
14,Indiana,1372,0.024387,1850,0.024136,NaN,NaN,NaN,NaN
15,Iowa,128,0.002275,145,0.001892,NaN,NaN,NaN,NaN
16,Kansas,123,0.002186,156,0.002035,NaN,NaN,NaN,NaN
17,Kentucky,185,0.003288,198,0.002583,NaN,NaN,NaN,NaN
18,Maine,6,0.000107,2,0.000026,NaN,NaN,NaN,NaN
19,Maryland,517,0.009190,655,0.008545,NaN,NaN,NaN,NaN
20,Massachusetts,118,0.002097,99,0.001292,NaN,NaN,NaN,NaN
21,Michigan,333,0.005919,360,0.004697,NaN,NaN,NaN,NaN
22,Minnesota,969,0.017224,1143,0.014912,NaN,NaN,NaN,NaN
23,Mississippi,86,0.001529,119,0.001553,NaN,NaN,NaN,NaN
24,Missouri,157,0.002791,146,0.001905,NaN,NaN,NaN,NaN
25,Montana,2,0.000036,4,0.000052,NaN,NaN,NaN,NaN
26,Nebraska,104,0.001849,107,0.001396,NaN,NaN,NaN,NaN
27,Nevada,1489,0.026467,1672,0.021813,NaN,NaN,NaN,NaN
28,New Hampshire,5,0.000089,1,0.000013,NaN,NaN,NaN,NaN
29,New Jersey,5645,0.100340,7237,0.094416,NaN,NaN,NaN,NaN
30,New Mexico,153,0.002720,118,0.001539,NaN,NaN,NaN,NaN
31,New York,12262,0.217956,17235,0.224853,NaN,NaN,NaN,NaN
32,North Carolina,831,0.014771,1766,0.023040,NaN,NaN,NaN,NaN
33,North Dakota,4,0.000071,5,0.000065,NaN,NaN,NaN,NaN
34,Ohio,205,0.003644,283,0.003692,NaN,NaN,NaN,NaN
35,Oklahoma,140,0.002488,247,0.003222,NaN,NaN,NaN,NaN
36,Oregon,501,0.008905,759,0.009902,NaN,NaN,NaN,NaN
37,Pennsylvania,1409,0.025045,1545,0.020157,NaN,NaN,NaN,NaN
38,Rhode Island,25,0.000444,28,0.000365,NaN,NaN,NaN,NaN
39,South Carolina,472,0.008390,523,0.006823,NaN,NaN,NaN,NaN
40,South Dakota,13,0.000231,16,0.000209,NaN,NaN,NaN,NaN
41,Tennessee,323,0.005741,446,0.005819,NaN,NaN,NaN,NaN
42,Texas,3058,0.054356,3901,0.050894,NaN,NaN,NaN,NaN
43,Utah,500,0.008887,529,0.006902,NaN,NaN,NaN,NaN
44,Vermont,8,0.000142,13,0.000170,NaN,NaN,NaN,NaN
45,Virginia,397,0.007057,535,0.006980,NaN,NaN,NaN,NaN
46,Washington,533,0.009474,672,0.008767,NaN,NaN,NaN,NaN
47,West Virginia,5,0.000089,10,0.000130,NaN,NaN,NaN,NaN
48,Wisconsin,552,0.009812,991,0.012929,NaN,NaN,NaN,NaN
49,Wyoming,31,0.000551,53,0.000691,NaN,NaN,NaN,NaN

In [35]:
df1 = pd.merge(df, df_2014, on='state')

In [36]:
df2 = pd.merge(df1, df_2013, on='state')
df2

,state,amount_2016,percent_2016,amount_2015,percent_2015,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,amount_2014,percent_2014,amount_2013
0,Alabama,199,0.003537,160,0.002087,NaN,NaN,NaN,NaN,142,0.002117,185.5
1,Alaska,2,0.000036,8,0.000104,NaN,NaN,NaN,NaN,2,0.000030,1.5
2,Arizona,273,0.004853,337,0.004397,NaN,NaN,NaN,NaN,212,0.003160,179.0
3,Arkansas,193,0.003431,256,0.003340,NaN,NaN,NaN,NaN,214,0.003190,176.0
4,California,15635,0.277911,22918,0.298995,NaN,NaN,NaN,NaN,19869,0.296154,20797.5
5,Colorado,522,0.009279,575,0.007502,NaN,NaN,NaN,NaN,505,0.007527,545.0
6,Connecticut,1295,0.023019,1969,0.025688,NaN,NaN,NaN,NaN,1484,0.022120,676.0
7,Delaware,284,0.005048,404,0.005271,NaN,NaN,NaN,NaN,338,0.005038,319.0
8,District of Columbia,63,0.001120,103,0.001344,NaN,NaN,NaN,NaN,70,0.001043,88.5
9,Florida,885,0.015731,1039,0.013555,NaN,NaN,NaN,NaN,881,0.013132,902.0
10,Georgia,698,0.012407,991,0.012929,NaN,NaN,NaN,NaN,681,0.010151,715.0
11,Hawaii,14,0.000249,16,0.000209,NaN,NaN,NaN,NaN,12,0.000179,6.0
12,Idaho,79,0.001404,76,0.000992,NaN,NaN,NaN,NaN,80,0.001192,57.0
13,Illinois,3286,0.058408,4063,0.053007,NaN,NaN,NaN,NaN,4770,0.071099,3506.0
14,Indiana,1372,0.024387,1850,0.024136,NaN,NaN,NaN,NaN,1610,0.023998,1108.5
15,Iowa,128,0.002275,145,0.001892,NaN,NaN,NaN,NaN,111,0.001654,115.0
16,Kansas,123,0.002186,156,0.002035,NaN,NaN,NaN,NaN,118,0.001759,137.5
17,Kentucky,185,0.003288,198,0.002583,NaN,NaN,NaN,NaN,157,0.002340,131.0
18,Maine,6,0.000107,2,0.000026,NaN,NaN,NaN,NaN,5,0.000075,3.5
19,Maryland,517,0.009190,655,0.008545,NaN,NaN,NaN,NaN,726,0.010821,581.5
20,Massachusetts,118,0.002097,99,0.001292,NaN,NaN,NaN,NaN,65,0.000969,59.0
21,Michigan,333,0.005919,360,0.004697,NaN,NaN,NaN,NaN,220,0.003279,244.5
22,Minnesota,969,0.017224,1143,0.014912,NaN,NaN,NaN,NaN,979,0.014592,1111.0
23,Mississippi,86,0.001529,119,0.001553,NaN,NaN,NaN,NaN,68,0.001014,84.5
24,Missouri,157,0.002791,146,0.001905,NaN,NaN,NaN,NaN,98,0.001461,126.0
25,Montana,2,0.000036,4,0.000052,NaN,NaN,NaN,NaN,3,0.000045,1.0
26,Nebraska,104,0.001849,107,0.001396,NaN,NaN,NaN,NaN,116,0.001729,122.5
27,Nevada,1489,0.026467,1672,0.021813,NaN,NaN,NaN,NaN,1563,0.023297,1570.5
28,New Hampshire,5,0.000089,1,0.000013,NaN,NaN,NaN,NaN,3,0.000045,3.5
29,New Jersey,5645,0.100340,7237,0.094416,NaN,NaN,NaN,NaN,6523,0.097228,5120.0
30,New Mexico,153,0.002720,118,0.001539,NaN,NaN,NaN,NaN,82,0.001222,99.5
31,New York,12262,0.217956,17235,0.224853,NaN,NaN,NaN,NaN,15297,0.228007,12453.0
32,North Carolina,831,0.014771,1766,0.023040,NaN,NaN,NaN,NaN,1352,0.020152,1159.5
33,North Dakota,4,0.000071,5,0.000065,NaN,NaN,NaN,NaN,5,0.000075,2.0
34,Ohio,205,0.003644,283,0.003692,NaN,NaN,NaN,NaN,200,0.002981,137.5
35,Oklahoma,140,0.002488,247,0.003222,NaN,NaN,NaN,NaN,188,0.002802,127.5
36,Oregon,501,0.008905,759,0.009902,NaN,NaN,NaN,NaN,683,0.010180,463.5
37,Pennsylvania,1409,0.025045,1545,0.020157,NaN,NaN,NaN,NaN,1387,0.020674,1230.0
38,Rhode Island,25,0.000444,28,0.000365,NaN,NaN,NaN,NaN,18,0.000268,19.5
39,South Carolina,472,0.008390,523,0.006823,NaN,NaN,NaN,NaN,403,0.006007,356.5
40,South Dakota,13,0.000231,16,0.000209,NaN,NaN,NaN,NaN,10,0.000149,13.0
41,Tennessee,323,0.005741,446,0.005819,NaN,NaN,NaN,NaN,292,0.004352,249.0
42,Texas,3058,0.054356,3901,0.050894,NaN,NaN,NaN,NaN,3538,0.052735,3256.5
43,Utah,500,0.008887,529,0.006902,NaN,NaN,NaN,NaN,363,0.005411,512.5
44,Vermont,8,0.000142,13,0.000170,NaN,NaN,NaN,NaN,15,0.000224,7.5
45,Virginia,397,0.007057,535,0.006980,NaN,NaN,NaN,NaN,360,0.005366,331.0
46,Washington,533,0.009474,672,0.008767,NaN,NaN,NaN,NaN,403,0.006007,345.5
47,West Virginia,5,0.000089,10,0.000130,NaN,NaN,NaN,NaN,10,0.000149,4.5
48,Wisconsin,552,0.009812,991,0.012929,NaN,NaN,NaN,NaN,676,0.010076,439.5
49,Wyoming,31,0.000551,53,0.000691,NaN,NaN,NaN,NaN,26,0.000388,26.5

In [37]:
df_total = df2[['state', 'amount_2016', 'amount_2015', 'amount_2014', 'amount_2013']]
df_total

                   state  amount_2016  amount_2015  amount_2014  amount_2013
0                Alabama          199          160          142        185.5
1                 Alaska            2            8            2          1.5
2                Arizona          273          337          212        179.0
3               Arkansas          193          256          214        176.0
4             California        15635        22918        19869      20797.5
5               Colorado          522          575          505        545.0
6            Connecticut         1295         1969         1484        676.0
7               Delaware          284          404          338        319.0
8   District of Columbia           63          103           70         88.5
9                Florida          885         1039          881        902.0
10               Georgia          698          991          681        715.0
11                Hawaii           14           16           12          6.0
12                 Idaho           79           76           80         57.0
13              Illinois         3286         4063         4770       3506.0
14               Indiana         1372         1850         1610       1108.5
15                  Iowa          128          145          111        115.0
16                Kansas          123          156          118        137.5
17              Kentucky          185          198          157        131.0
18                 Maine            6            2            5          3.5
19              Maryland          517          655          726        581.5
20         Massachusetts          118           99           65         59.0
21              Michigan          333          360          220        244.5
22             Minnesota          969         1143          979       1111.0
23           Mississippi           86          119           68         84.5
24              Missouri          157          146           98        126.0
25               Montana            2            4            3          1.0
26              Nebraska          104          107          116        122.5
27                Nevada         1489         1672         1563       1570.5
28         New Hampshire            5            1            3          3.5
29            New Jersey         5645         7237         6523       5120.0
30            New Mexico          153          118           82         99.5
31              New York        12262        17235        15297      12453.0
32        North Carolina          831         1766         1352       1159.5
33          North Dakota            4            5            5          2.0
34                  Ohio          205          283          200        137.5
35              Oklahoma          140          247          188        127.5
36                Oregon          501          759          683        463.5
37          Pennsylvania         1409         1545         1387       1230.0
38          Rhode Island           25           28           18         19.5
39        South Carolina          472          523          403        356.5
40          South Dakota           13           16           10         13.0
41             Tennessee          323          446          292        249.0
42                 Texas         3058         3901         3538       3256.5
43                  Utah          500          529          363        512.5
44               Vermont            8           13           15          7.5
45              Virginia          397          535          360        331.0
46            Washington          533          672          403        345.5
47         West Virginia            5           10           10          4.5
48             Wisconsin          552          991          676        439.5
49               Wyoming           31           53           26         26.5

In [43]:
df_total = df_total.append(df_total.sum(numeric_only=True), ignore_index=True)

In [44]:
df_total

                   state  amount_2016  amount_2015  amount_2014  amount_2013
0                Alabama        199.0        160.0        142.0        185.5
1                 Alaska          2.0          8.0          2.0          1.5
2                Arizona        273.0        337.0        212.0        179.0
3               Arkansas        193.0        256.0        214.0        176.0
4             California      15635.0      22918.0      19869.0      20797.5
5               Colorado        522.0        575.0        505.0        545.0
6            Connecticut       1295.0       1969.0       1484.0        676.0
7               Delaware        284.0        404.0        338.0        319.0
8   District of Columbia         63.0        103.0         70.0         88.5
9                Florida        885.0       1039.0        881.0        902.0
10               Georgia        698.0        991.0        681.0        715.0
11                Hawaii         14.0         16.0         12.0          6.0
12                 Idaho         79.0         76.0         80.0         57.0
13              Illinois       3286.0       4063.0       4770.0       3506.0
14               Indiana       1372.0       1850.0       1610.0       1108.5
15                  Iowa        128.0        145.0        111.0        115.0
16                Kansas        123.0        156.0        118.0        137.5
17              Kentucky        185.0        198.0        157.0        131.0
18                 Maine          6.0          2.0          5.0          3.5
19              Maryland        517.0        655.0        726.0        581.5
20         Massachusetts        118.0         99.0         65.0         59.0
21              Michigan        333.0        360.0        220.0        244.5
22             Minnesota        969.0       1143.0        979.0       1111.0
23           Mississippi         86.0        119.0         68.0         84.5
24              Missouri        157.0        146.0         98.0        126.0
25               Montana          2.0          4.0          3.0          1.0
26              Nebraska        104.0        107.0        116.0        122.5
27                Nevada       1489.0       1672.0       1563.0       1570.5
28         New Hampshire          5.0          1.0          3.0          3.5
29            New Jersey       5645.0       7237.0       6523.0       5120.0
30            New Mexico        153.0        118.0         82.0         99.5
31              New York      12262.0      17235.0      15297.0      12453.0
32        North Carolina        831.0       1766.0       1352.0       1159.5
33          North Dakota          4.0          5.0          5.0          2.0
34                  Ohio        205.0        283.0        200.0        137.5
35              Oklahoma        140.0        247.0        188.0        127.5
36                Oregon        501.0        759.0        683.0        463.5
37          Pennsylvania       1409.0       1545.0       1387.0       1230.0
38          Rhode Island         25.0         28.0         18.0         19.5
39        South Carolina        472.0        523.0        403.0        356.5
40          South Dakota         13.0         16.0         10.0         13.0
41             Tennessee        323.0        446.0        292.0        249.0
42                 Texas       3058.0       3901.0       3538.0       3256.5
43                  Utah        500.0        529.0        363.0        512.5
44               Vermont          8.0         13.0         15.0          7.5
45              Virginia        397.0        535.0        360.0        331.0
46            Washington        533.0        672.0        403.0        345.5
47         West Virginia          5.0         10.0         10.0          4.5
48             Wisconsin        552.0        991.0        676.0        439.5
49               Wyoming         31.0         53.0         26.0         26.5
50                   NaN      56089.0      76484.0      66933.0      59907.5

In [45]:
df_total['Total'] = df_total.amount_2016 + df_total.amount_2015 + df_total.amount_2014 + df_total.amount_2013

In [46]:
df_total

,state,amount_2016,amount_2015,amount_2014,amount_2013,Total
0,Alabama,199.0,160.0,142.0,185.5,686.5
1,Alaska,2.0,8.0,2.0,1.5,13.5
2,Arizona,273.0,337.0,212.0,179.0,1001.0
3,Arkansas,193.0,256.0,214.0,176.0,839.0
4,California,15635.0,22918.0,19869.0,20797.5,79219.5
5,Colorado,522.0,575.0,505.0,545.0,2147.0
6,Connecticut,1295.0,1969.0,1484.0,676.0,5424.0
7,Delaware,284.0,404.0,338.0,319.0,1345.0
8,District of Columbia,63.0,103.0,70.0,88.5,324.5
9,Florida,885.0,1039.0,881.0,902.0,3707.0
10,Georgia,698.0,991.0,681.0,715.0,3085.0
11,Hawaii,14.0,16.0,12.0,6.0,48.0
12,Idaho,79.0,76.0,80.0,57.0,292.0
13,Illinois,3286.0,4063.0,4770.0,3506.0,15625.0
14,Indiana,1372.0,1850.0,1610.0,1108.5,5940.5
15,Iowa,128.0,145.0,111.0,115.0,499.0
16,Kansas,123.0,156.0,118.0,137.5,534.5
17,Kentucky,185.0,198.0,157.0,131.0,671.0
18,Maine,6.0,2.0,5.0,3.5,16.5
19,Maryland,517.0,655.0,726.0,581.5,2479.5
20,Massachusetts,118.0,99.0,65.0,59.0,341.0
21,Michigan,333.0,360.0,220.0,244.5,1157.5
22,Minnesota,969.0,1143.0,979.0,1111.0,4202.0
23,Mississippi,86.0,119.0,68.0,84.5,357.5
24,Missouri,157.0,146.0,98.0,126.0,527.0
25,Montana,2.0,4.0,3.0,1.0,10.0
26,Nebraska,104.0,107.0,116.0,122.5,449.5
27,Nevada,1489.0,1672.0,1563.0,1570.5,6294.5
28,New Hampshire,5.0,1.0,3.0,3.5,12.5
29,New Jersey,5645.0,7237.0,6523.0,5120.0,24525.0
30,New Mexico,153.0,118.0,82.0,99.5,452.5
31,New York,12262.0,17235.0,15297.0,12453.0,57247.0
32,North Carolina,831.0,1766.0,1352.0,1159.5,5108.5
33,North Dakota,4.0,5.0,5.0,2.0,16.0
34,Ohio,205.0,283.0,200.0,137.5,825.5
35,Oklahoma,140.0,247.0,188.0,127.5,702.5
36,Oregon,501.0,759.0,683.0,463.5,2406.5
37,Pennsylvania,1409.0,1545.0,1387.0,1230.0,5571.0
38,Rhode Island,25.0,28.0,18.0,19.5,90.5
39,South Carolina,472.0,523.0,403.0,356.5,1754.5
40,South Dakota,13.0,16.0,10.0,13.0,52.0
41,Tennessee,323.0,446.0,292.0,249.0,1310.0
42,Texas,3058.0,3901.0,3538.0,3256.5,13753.5
43,Utah,500.0,529.0,363.0,512.5,1904.5
44,Vermont,8.0,13.0,15.0,7.5,43.5
45,Virginia,397.0,535.0,360.0,331.0,1623.0
46,Washington,533.0,672.0,403.0,345.5,1953.5
47,West Virginia,5.0,10.0,10.0,4.5,29.5
48,Wisconsin,552.0,991.0,676.0,439.5,2658.5
49,Wyoming,31.0,53.0,26.0,26.5,136.5
50,NaN,56089.0,76484.0,66933.0,59907.5,259413.5

In [48]:
df_total.sort_values(by= 'Total', ascending = False)

,state,amount_2016,amount_2015,amount_2014,amount_2013,Total
50,NaN,56089.0,76484.0,66933.0,59907.5,259413.5
4,California,15635.0,22918.0,19869.0,20797.5,79219.5
31,New York,12262.0,17235.0,15297.0,12453.0,57247.0
29,New Jersey,5645.0,7237.0,6523.0,5120.0,24525.0
13,Illinois,3286.0,4063.0,4770.0,3506.0,15625.0
42,Texas,3058.0,3901.0,3538.0,3256.5,13753.5
27,Nevada,1489.0,1672.0,1563.0,1570.5,6294.5
14,Indiana,1372.0,1850.0,1610.0,1108.5,5940.5
37,Pennsylvania,1409.0,1545.0,1387.0,1230.0,5571.0
6,Connecticut,1295.0,1969.0,1484.0,676.0,5424.0
32,North Carolina,831.0,1766.0,1352.0,1159.5,5108.5
22,Minnesota,969.0,1143.0,979.0,1111.0,4202.0
9,Florida,885.0,1039.0,881.0,902.0,3707.0
10,Georgia,698.0,991.0,681.0,715.0,3085.0
48,Wisconsin,552.0,991.0,676.0,439.5,2658.5
19,Maryland,517.0,655.0,726.0,581.5,2479.5
36,Oregon,501.0,759.0,683.0,463.5,2406.5
5,Colorado,522.0,575.0,505.0,545.0,2147.0
46,Washington,533.0,672.0,403.0,345.5,1953.5
43,Utah,500.0,529.0,363.0,512.5,1904.5
39,South Carolina,472.0,523.0,403.0,356.5,1754.5
45,Virginia,397.0,535.0,360.0,331.0,1623.0
7,Delaware,284.0,404.0,338.0,319.0,1345.0
41,Tennessee,323.0,446.0,292.0,249.0,1310.0
21,Michigan,333.0,360.0,220.0,244.5,1157.5
2,Arizona,273.0,337.0,212.0,179.0,1001.0
3,Arkansas,193.0,256.0,214.0,176.0,839.0
34,Ohio,205.0,283.0,200.0,137.5,825.5
35,Oklahoma,140.0,247.0,188.0,127.5,702.5
0,Alabama,199.0,160.0,142.0,185.5,686.5
17,Kentucky,185.0,198.0,157.0,131.0,671.0
16,Kansas,123.0,156.0,118.0,137.5,534.5
24,Missouri,157.0,146.0,98.0,126.0,527.0
15,Iowa,128.0,145.0,111.0,115.0,499.0
30,New Mexico,153.0,118.0,82.0,99.5,452.5
26,Nebraska,104.0,107.0,116.0,122.5,449.5
23,Mississippi,86.0,119.0,68.0,84.5,357.5
20,Massachusetts,118.0,99.0,65.0,59.0,341.0
8,District of Columbia,63.0,103.0,70.0,88.5,324.5
12,Idaho,79.0,76.0,80.0,57.0,292.0
49,Wyoming,31.0,53.0,26.0,26.5,136.5
38,Rhode Island,25.0,28.0,18.0,19.5,90.5
40,South Dakota,13.0,16.0,10.0,13.0,52.0
11,Hawaii,14.0,16.0,12.0,6.0,48.0
44,Vermont,8.0,13.0,15.0,7.5,43.5
47,West Virginia,5.0,10.0,10.0,4.5,29.5
18,Maine,6.0,2.0,5.0,3.5,16.5
33,North Dakota,4.0,5.0,5.0,2.0,16.0
1,Alaska,2.0,8.0,2.0,1.5,13.5
28,New Hampshire,5.0,1.0,3.0,3.5,12.5
25,Montana,2.0,4.0,3.0,1.0,10.0